name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: make Install
    - name: Lint with pylint
      run: make lint
    - name: Test with pytest
      run: make test
    - name: make distcheck
      run: make distcheck
